### ISSUE TITLE
Problems while installing

### ISSUE THREAD

**Issue by Chrisstar56** [phiilu/mailman#30]
The installation always fails with the following error:
```
18618 warn mailman@1.0.2 No repository field.
18619 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
18620 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
18621 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
18621 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
18621 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
18621 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
18622 verbose stack Error: mariasql@0.2.6 install: `node-gyp rebuild`
18622 verbose stack Exit status 1
18622 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
18622 verbose stack Exit status 1
18622 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
18622 verbose stack     at EventEmitter.emit (events.js:182:13)
18622 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18622 verbose stack     at ChildProcess.emit (events.js:182:13)
18622 verbose stack     at maybeClose (internal/child_process.js:962:16)
18622 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
18623 verbose pkgid mariasql@0.2.6
18624 verbose cwd /var/www/mail/mailman
18625 verbose Linux 4.9.0-7-amd64
18626 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
18627 verbose node v10.8.0
18628 verbose npm  v6.2.0
18629 error code ELIFECYCLE
18630 error errno 1
18631 error mariasql@0.2.6 install: `node-gyp rebuild`
18631 error Exit status 1
18632 error Failed at the mariasql@0.2.6 install script.
18632 error This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by phiilu** [comment]
This seems like a problem with `node-gyp` which is most of the time a problem that you don't have the `build-tools` or native binaries for `mysql`  installed on your system. I would suggest googling `install node-gyp build tools` or using my docker image to install Mailman.
